routes/web.php
<?php

use App\Http\Controllers\Admin\Estate\CityController;
use App\Http\Controllers\Admin\Estate\AddWriteAttachmentsToAdController;
use App\Http\Controllers\Admin\Estate\AgentController;
use App\Http\Controllers\Admin\Estate\AttachedController;
use App\Http\Controllers\Admin\Estate\CategoryController;
use App\Http\Controllers\Admin\Estate\CountryControoler;
use App\Http\Controllers\Admin\Estate\GetAttachedController;
use App\Http\Controllers\Admin\Estate\GetSubCategoryController;
use App\Http\Controllers\Admin\Estate\WriteAttachmentController;
use App\Http\Controllers\Admin\ServiceController;
use App\Http\Controllers\Admin\SubCategoryController;
use App\Http\Controllers\Web\AdController;
use App\Http\Controllers\Web\CommercialController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'website.index')->name('website.index');
Route::view('/about', 'website.about')->name('website.about');
Route::view('/services', 'website.services')->name('website.services');
Route::view('/contact', 'website.contact')->name('website.contact');
Route::view('/faq', 'website.FAQ')->name('website.FAQ');
Route::view('/terms-conditions', 'website.terms-conditions')->name('website.terms-conditions');
Route::view('/privacy', 'website.terms-conditions')->name('website.privacy');
Route::view('/estate', 'website.estate')->name('website.estate');

Route::get('/commercial', [\App\Http\Controllers\web\PagesController::class, 'commercial'])->name('website.commercial');
Route::get('/commerical/{slug}', [CommercialController::class, 'show'])->name('commercial.show');
Route::get('/commercial/download-pdf/{slug}', [CommercialController::class, 'download'])->name('commercial.download');
Route::get('/store', [\App\Http\Controllers\web\PagesController::class, 'store'])->name('website.store');

Route::get('/register', [\App\Http\Controllers\Web\Auth\RegisterController::class, 'register'])->name('register.index');
Route::post('/register', [\App\Http\Controllers\Web\Auth\RegisterController::class, 'submit'])->name('register.submit');
Route::get('/login', [\App\Http\Controllers\Web\Auth\LoginController::class, 'login'])->name('login.index');
Route::post('/login', [\App\Http\Controllers\Web\Auth\LoginController::class, 'submit'])->name('login.submit');
Route::get('/products', [\App\Http\Controllers\Web\Store\StoreController::class, 'index'])->name('store.index');
Route::get('/store/category/{slug}', [\App\Http\Controllers\Web\Store\StoreController::class, 'category'])->name('store.category');
Route::get('store/product/{slug}', [\App\Http\Controllers\Web\Store\ProductController::class, 'index'])->name('product.index');
Route::get('store/search/', [\App\Http\Controllers\Web\Store\ProductController::class, 'search'])->name('product.search');
Route::get('store/wishlist', [\App\Http\Controllers\Web\Store\WishlistController::class, 'index'])->name('store.wishlist');
Route::get('store/wishlist/{slug}', [\App\Http\Controllers\Web\Store\WishlistController::class, 'add'])->name('store.wishlist.add');
Route::get('store/wishlist/remove/{id}', [\App\Http\Controllers\Web\Store\WishlistController::class, 'remove'])->name('store.wishlist.remove');
Route::get('coupons', [\App\Http\Controllers\Web\CouponController::class, 'index'])->name('coupon.index');
Route::get('coupons/search/', [\App\Http\Controllers\Web\CouponController::class, 'search'])->name('coupon.search');
Route::get('/ads', [\App\Http\Controllers\Web\AdController::class, 'index'])->name('ads.index');
Route::get('/ad/search/', [\App\Http\Controllers\Web\AdController::class, 'search'])->name('ads.search');
Route::get('/ads/country/{country_id}', [AdController::class, 'countryAd'])->name('ads.country');
Route::get('/ads/{slug}', [\App\Http\Controllers\Web\AdController::class, 'show'])->name('ads.show');
Route::get('/ad/{slug}', [\App\Http\Controllers\Web\AdController::class, 'dwonload'])->name('ads.chart_download');
Route::get('/service/{slug}', [\App\Http\Controllers\Web\ServicesController::class, 'show'])->name('service.show');
Route::post('/contact/store', [\App\Http\Controllers\Admin\ContactUsController::class, 'store'])->name('contact.store');


Route::get('/cities/{id}', [\App\Http\Controllers\Web\AdController::class, 'getCities'])->name('ads.cities');
Route::group(['middleware' => 'auth:web'], function () {
    //    Start Cart Routers
    Route::get('/my-cart', [\App\Http\Controllers\Web\Store\CartController::class, 'index'])->name('cart.index');
    Route::post('/my-cart/add/{slug}', [\App\Http\Controllers\Web\Store\CartController::class, 'add'])->name('cart.add');
    Route::get('my-cart/remove/{id}', [\App\Http\Controllers\Web\Store\CartController::class, 'remove'])->name('cart.remove');
    //    End Cart Routers

    //    Start Checkout Routers
    Route::get('/store/payment-checkout', [\App\Http\Controllers\Web\Store\PaymentController::class, 'index'])->name('payment.checkout');
    Route::get('/store/payment-checkout/shopper', [\App\Http\Controllers\Web\Store\PaymentController::class, 'shopper'])->name('payment.shopper');
    Route::view('/store/payment-done', 'website.checkout-status')->name('payment.status');

    //    Start Order Information Route
    Route::post('/store/order-information', [\App\Http\Controllers\Web\Store\OrderController::class, 'store'])->name('order.store');
    Route::post('/store/order-information/update', [\App\Http\Controllers\Web\Store\OrderController::class, 'update'])->name('order.update');

    //    Start Evaluate Routers
    Route::post('/store/product/{slug}/evaluate', [\App\Http\Controllers\Web\Store\EvaluateController::class, 'store'])->name('product.evaluate');
    //    Start Get Coupon Route
    Route::get('coupons/get/{id}', [\App\Http\Controllers\Web\CouponController::class, 'get'])->name('coupon.get');

    //    Start Routes of Ads
    Route::get('/estate/create', [\App\Http\Controllers\Web\AdController::class, 'create'])->name('ads.create');

    Route::post('/estate/submit', [\App\Http\Controllers\Web\AdController::class, 'store'])->name('ads.store');

    //    get cities

});

Route::view('/admin', 'admin.index');


Route::group(['middleware' => 'auth:admin', 'as' => 'admin.', 'name' => 'admin', 'prefix' => 'admin'], function () {
    Route::get('/', ['App\Http\Controllers\Admin\AdminController', 'index'])->name('index');

    Route::group(['as' => 'store.', 'name' => 'admin', 'prefix' => '/store'], function () {
        Route::get('/', [\App\Http\Controllers\Admin\Store\StoreController::class, 'index'])->name('store.index');
        Route::get('/categories/create', [\App\Http\Controllers\Admin\Store\CategoryController::class, 'create'])->name('category.create');
        Route::post('/categories/store', [\App\Http\Controllers\Admin\Store\CategoryController::class, 'store'])->name('category.store');
        Route::get('/categories', [\App\Http\Controllers\Admin\Store\CategoryController::class, 'index'])->name('category');
        Route::get('/categories/{slug}', [\App\Http\Controllers\Admin\Store\CategoryController::class, 'show'])->name('category.show');
        Route::get('/categories/edit/{slug}', [\App\Http\Controllers\Admin\Store\CategoryController::class, 'edit'])->name('category.edit');
        Route::post('/categories/update/{id}', ['App\Http\Controllers\Admin\Store\CategoryController', 'update'])->name('category.update');
        Route::post('categories/delete/{slug}', [\App\Http\Controllers\Admin\Store\CategoryController::class, 'destroy'])->name('category.destroy');
        Route::resource('sizes', \App\Http\Controllers\Admin\Store\SizeController::class)->parameters(['sizes' => 'id']);
        Route::resource('colors', \App\Http\Controllers\Admin\Store\ColorController::class)->parameters(['colors' => 'id']);
        Route::resource('products', \App\Http\Controllers\Admin\Store\ProductController::class)->parameters(['products' => 'slug']);
        Route::resource('orders', \App\Http\Controllers\Admin\Store\OrderController::class)->parameters(['orders' => 'id']);
        Route::resource('coupons', \App\Http\Controllers\Admin\CouponController::class)->parameters(['orders' => 'id']);
    });

    Route::resource('/service', ServiceController::class)->parameters(['service' => 'slug']);
    Route::group(['as' => 'estates.', 'name' => 'admin', 'prefix' => '/estate'], function () {
        Route::resource('/citys', CityController::class)->parameters(['citys' => 'id']);
        Route::resource('/categories', CategoryController::class)->parameters(['categories' => 'id']);
        Route::resource('/sub-category', SubCategoryController::class)->parameters(['categories' => 'id']);
        Route::resource('/countries', CountryControoler::class)->parameters(['countries' => 'id']);
        Route::resource('/ads', \App\Http\Controllers\Admin\Estate\AdController::class)->parameters(['ads' => 'id']);
        Route::get('/ads/status/{id}', [\App\Http\Controllers\Admin\Estate\AdController::class, 'status'])->name('ads.status');
        Route::resource('/agents', AgentController::class)->parameters(['agents' => 'id']);
        Route::resource('/attacheds', AttachedController::class)->parameters(['attacheds' => 'id']);
        Route::resource('/attachments', WriteAttachmentController::class)->parameters(['attachments' => 'id']);
        Route::get('/add/attachments/{slug}', [AddWriteAttachmentsToAdController::class, 'create'])->name('attachment.ad.add');
        Route::post('/create/attachments/{slug}', [AddWriteAttachmentsToAdController::class, 'store'])->name('attachment.ad.store');

app/Http/Controllers/Admin/Estate/AddWriteAttachmentsToAdController.php
<?php

namespace App\Http\Controllers\Admin\Estate;

use App\Http\Controllers\Controller;
use App\Models\Ad;
use App\Models\AdWriteAttachment;
use App\Models\PivotAdAttached;
use App\Models\PivotAdWriteAttachment;
use Illuminate\Http\Request;

class AddWriteAttachmentsToAdController extends Controller
{
    public function create($slug)
    {
        $ad = Ad::query()->where('slug', $slug)->first();
        $attachments = AdWriteAttachment::query()->get();
        return view('admin.pages.Estates.writeAttachments.addAttachment.create', compact('attachments', 'ad'));
    }

    public function store(Request $request, $slug)
    {
        $ad = Ad::query()->where('slug', $slug)->first();

        $ad->writeAttachments()->detach();
        if ($request->attachCh)
        {
            foreach ($request->attachCh as $key => $item)
            {
                PivotAdWriteAttachment::query()->create([
                    'ad_id' => $ad->id,
                    'ad_write_attachment_id' => $item,
                    'body' => $request->attach[$key]
                ]);
            }
        }
        session()->flash('success', 'تم اضافة المرفق بنجاح');
        return back();
    }
}

app/Http/Controllers/Admin/Estate/AgentController.php
<?php

namespace App\Http\Controllers\Admin\Estate;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Estate\CreateOrUpdateAgentsRequest;
use App\Models\AdAgent;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class AgentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $agents = AdAgent::query()->paginate(10);
        return view('admin.pages.Estates.agents.index', compact('agents'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.Estates.agents.create-update');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateOrUpdateAgentsRequest $request)
    {
        $time = time();
        $fileName = $request->image->getClientOriginalName();
        $image = Image::make($request->image->getRealPath());
        $image->resize(100,100);
        $image->save(public_path('storage/Images/agents/'. $time. $fileName));
        AdAgent::query()->create([
            'name' => $request->name,
            'rate' => $request->rate,
            'description' => $request->description,
            'email' => $request->email,
            'city' => $request->city,
            'phone' => $request->phone,
            'image' => 'Images/agents/'.$time. $fileName
        ]);
        session()->flash('success', 'تم اضافة الوكيل بنجاح');
        return redirect()->route('admin.estates.agents.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $agent = AdAgent::query()->findOrFail($id);
        return view('admin.pages.Estates.agents.create-update', compact('agent'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CreateOrUpdateAgentsRequest $request, $id)
    {
        $agent = AdAgent::query()->findOrFail($id);
        $agent->name = $request->name;
        $agent->email = $request->email;
        $agent->phone = $request->phone;
        $agent->description = $request->description;

        $agent->city = $request->city;
        $agent->rate = $request->rate;
        if ($request->has('image'))
        {
            $time = time();
            Storage::delete('/public/'. $agent->image);
            $fileName = $request->image->getClientOriginalName();
            $image = Image::make($request->image->getRealPath());
            $image->resize(100,100);
            $image->save(public_path('storage/Images/agents/'. $time. $fileName));
            $agent->image = 'Images/agents/'.$time. $fileName;
        }
        $agent->save();
        session()->flash('success', 'تم معلومات الوكيل بنجاح');
        return redirect()->route('admin.estates.agents.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $agent = AdAgent::query()->findOrFail($id);
        Storage::delete('/public/'. $agent->image);
        $agent->delete();
        session()->flash('success', 'تم حذف الوكيل بنجاح');
        return redirect()->route('admin.estates.agents.index');
    }
}

app/Http/Controllers/Admin/Estate/AttachedController.php
<?php

namespace App\Http\Controllers\Admin\Estate;

use App\Http\Controllers\Controller;
use App\Models\AdAttached;
use App\Models\AdCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class AttachedController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $attacheds = AdAttached::query()->paginate(10);
        return view('admin.pages.Estates.attacheds.index', compact('attacheds'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.Estates.attacheds.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'attached' => 'required|max:100',
        ],[
            'name.required' => 'يرجي كتابة الاسم',
            'name.max' => 'اكبر عدد لحروف الاسم 100 حرف',
            'icon.required' => 'الايكون مطلوبة'
        ]);
        AdAttached::query()->create([
            'attached' => $request->attached,
            'icon' => $request->icon->store('Ads/attachment/icon', 'public')
        ]);
        session()->flash('success', 'تم اضافة المرفق بنجاح');
        return redirect()->route('admin.estates.attacheds.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $attached = AdAttached::query()->findOrFail($id);
        Storage::delete('/public/'. $attached->icon);
        $attached->delete();
        session()->flash('success', 'تم حذف المرفق بنجاح');
        return back();
    }
}

resources/views/admin/pages/Estates/ads/index.blade.php
@extends('admin.layouts.app')

@section('title', 'اعلانات العقارات')

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="col-12">
                        <a href="{{ route('admin.estates.ads.create') }}" class="btn btn-success my-2">اضافة عقار</a>
                    </div>
                    <table class="table m-auto table-striped table-responsive-sm">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>اسم الاعلان</th>
                            <th>الحالة</th>
                            <th>عمليات</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($ads as $key => $item)
                            <tr>
                                <td>{{ $key+1 }}</td>
                                <td>{{ $item->title }}</td>
                                <td>
                                    @if($item->ad_status == 0)
                                        <span class="text-danger">معلق</span>
                                    @elseif($item->ad_status == 1)
                                        <span class="text-success">مفعل</span>
                                    @elseif($item->ad_status == 2)
                                        <span class="text-info">غير مفعل</span>
                                    @endif

                                </td>
                                <td class="d-flex">
                                    <a href="{{ route('admin.estates.ads.show', $item->id) }}"
                                       class="btn btn-info">عرض</a>
                                    <a href="{{ route('admin.estates.ads.edit', $item->id) }}"
                                       class="btn btn-secondary mx-2">تعديل</a>
                                    <form action="{{ route('admin.estates.ads.destroy', $item->id) }}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger">حذف</button>
                                    </form>
                                    <a href="{{ route('admin.estates.ads.status', $item->id) }}" class="btn btn-dark mx-2">
                                        @if($item->ad_status == 0)
                                            تفعيل
                                        @elseif($item->ad_status == 1)
                                            الغاء التفعيل
                                        @endif
                                    </a>
                                    <a class="btn btn-light" href="{{ route('admin.estates.attachment.ad.add', $item->slug) }}">اضافة مرفق كتابي</a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/pages/Estates/ads/show.blade.php
@extends('admin.layouts.app')

@section('title', $ad->title)

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body row">
                            <div class="p-2 col-md-6 col-12">
                                <h4>اسم المعلن</h4>
                                <p class="text-gray">
                                    {{ $ad->advertiser_name }}
                                </p>
                            </div>
                            <div class="p-2 col-md-6 col-12">
                                <h4>البريد الالكتروني للمعلن</h4>
                                <p class="text-gray">
                                    {{ $ad->advertiser_email }}
                                </p>
                            </div>
                            <div class="p-2 col-md-6 col-12">
                                <h4>رقم هاتف المعلن الاول</h4>
                                <p class="text-gray">
                                    {{ $ad->phone }}
                                </p>
                            </div>
                            <div class="p-2 col-md-6 col-12">
                                <h4>رقم هاتف المعلن الثاني</h4>
                                <p class="text-gray">
                                    {{ $ad->second_phone }}
                                </p>
                            </div>
                            <div class="col-12">
                                <hr>
                            </div>
                            <div class="p-2 col-md-6 col-12">
                                <h4>عنوان الاعلان</h4>
                                <p class="text-gray">
                                    {{ $ad->title }}
                                </p>
                            </div>
                            <div class="p-2 col-md-6 col-12">
                                <h4>السعر</h4>
                                <p class="text-gray">
                                    {{ $ad->price }}
                                </p>
                            </div>
                            <div class="p-2 col-md-6 col-12">
                                <h4>المساحة</h4>
                                <p class="text-gray">
                                    {{ $ad->space }}
                                </p>
                            </div>
                            <div class="p-2 col-md-6 col-12">
                                <h4>حالة الاعلان</h4>
                                <p class="text-gray">
                                    {{ $ad->ad_status == 0 ? 'للبيع' : 'للإيجار' }}
                                </p>
                            </div>
                            <div class="p-2 col-md-6 col-12">
                                <h4>عنوان الاعلان الجغرافي</h4>
                                <p class="text-gray">
                                    {{ $ad->address }}
                                </p>
                            </div>
                            <div class="p-2 col-md-6 col-12">
                                <h4>البلد</h4>
                                <p class="text-gray">
                                    {{ $ad->city->country->name }}
                                </p>
                            </div>
                            <div class="p-2 col-md-6 col-12">
                                <h4>المدينة</h4>
                                <p class="text-gray">
                                    {{ $ad->city->name }}
                                </p>
                            </div>
                            <div class="p-2 col-md-6 col-12">
                                <h4>القسم</h4>
                                <p class="text-gray">
                                    {{ $ad->category->name }}
                                </p>
                            </div>
                            <div class="col-12">
                                <hr>
                            </div>
                            <div class="col-12">
                                <a href="{{ route('admin.estates.ads.edit', $ad->id) }}" class="btn btn-info">تعديل</a>
                                <a href="{{ url()->previous() }}" class="btn badge-dark">رجوع</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection