routes/web.php
<?php

use App\Http\Controllers\Admin\Estate\CityController;
use App\Http\Controllers\Admin\Estate\AddWriteAttachmentsToAdController;
use App\Http\Controllers\Admin\Estate\AgentController;
use App\Http\Controllers\Admin\Estate\AttachedController;
use App\Http\Controllers\Admin\Estate\CategoryController;
use App\Http\Controllers\Admin\Estate\CountryControoler;
use App\Http\Controllers\Admin\Estate\GetAttachedController;
use App\Http\Controllers\Admin\Estate\GetSubCategoryController;
use App\Http\Controllers\Admin\Estate\WriteAttachmentController;
use App\Http\Controllers\Admin\ServiceController;
use App\Http\Controllers\Admin\SubCategoryController;
use App\Http\Controllers\Web\AdController;
use App\Http\Controllers\Web\CommercialController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'website.index')->name('website.index');
Route::view('/about', 'website.about')->name('website.about');
Route::view('/services', 'website.services')->name('website.services');
Route::view('/contact', 'website.contact')->name('website.contact');
Route::view('/faq', 'website.FAQ')->name('website.FAQ');
Route::view('/terms-conditions', 'website.terms-conditions')->name('website.terms-conditions');
Route::view('/privacy', 'website.terms-conditions')->name('website.privacy');
Route::view('/estate', 'website.estate')->name('website.estate');

Route::get('/commercial', [\App\Http\Controllers\web\PagesController::class, 'commercial'])->name('website.commercial');
Route::get('/commerical/{slug}', [CommercialController::class, 'show'])->name('commercial.show');
Route::get('/commercial/download-pdf/{slug}', [CommercialController::class, 'download'])->name('commercial.download');
Route::get('/store', [\App\Http\Controllers\web\PagesController::class, 'store'])->name('website.store');

Route::get('/register', [\App\Http\Controllers\Web\Auth\RegisterController::class, 'register'])->name('register.index');
Route::post('/register', [\App\Http\Controllers\Web\Auth\RegisterController::class, 'submit'])->name('register.submit');
Route::get('/login', [\App\Http\Controllers\Web\Auth\LoginController::class, 'login'])->name('login.index');
Route::post('/login', [\App\Http\Controllers\Web\Auth\LoginController::class, 'submit'])->name('login.submit');
Route::get('/products', [\App\Http\Controllers\Web\Store\StoreController::class, 'index'])->name('store.index');
Route::get('/store/category/{slug}', [\App\Http\Controllers\Web\Store\StoreController::class, 'category'])->name('store.category');
Route::get('store/product/{slug}', [\App\Http\Controllers\Web\Store\ProductController::class, 'index'])->name('product.index');
Route::get('store/search/', [\App\Http\Controllers\Web\Store\ProductController::class, 'search'])->name('product.search');
Route::get('store/wishlist', [\App\Http\Controllers\Web\Store\WishlistController::class, 'index'])->name('store.wishlist');
Route::get('store/wishlist/{slug}', [\App\Http\Controllers\Web\Store\WishlistController::class, 'add'])->name('store.wishlist.add');
Route::get('store/wishlist/remove/{id}', [\App\Http\Controllers\Web\Store\WishlistController::class, 'remove'])->name('store.wishlist.remove');
Route::get('coupons', [\App\Http\Controllers\Web\CouponController::class, 'index'])->name('coupon.index');
Route::get('coupons/search/', [\App\Http\Controllers\Web\CouponController::class, 'search'])->name('coupon.search');
Route::get('/ads', [\App\Http\Controllers\Web\AdController::class, 'index'])->name('ads.index');
Route::get('/ad/search/', [\App\Http\Controllers\Web\AdController::class, 'search'])->name('ads.search');
Route::get('/ads/country/{country_id}', [AdController::class, 'countryAd'])->name('ads.country');
Route::get('/ads/{slug}', [\App\Http\Controllers\Web\AdController::class, 'show'])->name('ads.show');
Route::get('/ad/{slug}', [\App\Http\Controllers\Web\AdController::class, 'dwonload'])->name('ads.chart_download');
Route::get('/service/{slug}', [\App\Http\Controllers\Web\ServicesController::class, 'show'])->name('service.show');
Route::post('/contact/store', [\App\Http\Controllers\Admin\ContactUsController::class, 'store'])->name('contact.store');


Route::get('/cities/{id}', [\App\Http\Controllers\Web\AdController::class, 'getCities'])->name('ads.cities');
Route::group(['middleware' => 'auth:web'], function () {
    //    Start Cart Routers
    Route::get('/my-cart', [\App\Http\Controllers\Web\Store\CartController::class, 'index'])->name('cart.index');
    Route::post('/my-cart/add/{slug}', [\App\Http\Controllers\Web\Store\CartController::class, 'add'])->name('cart.add');
    Route::get('my-cart/remove/{id}', [\App\Http\Controllers\Web\Store\CartController::class, 'remove'])->name('cart.remove');
    //    End Cart Routers

    //    Start Checkout Routers
    Route::get('/store/payment-checkout', [\App\Http\Controllers\Web\Store\PaymentController::class, 'index'])->name('payment.checkout');
    Route::get('/store/payment-checkout/shopper', [\App\Http\Controllers\Web\Store\PaymentController::class, 'shopper'])->name('payment.shopper');
    Route::view('/store/payment-done', 'website.checkout-status')->name('payment.status');

    //    Start Order Information Route
    Route::post('/store/order-information', [\App\Http\Controllers\Web\Store\OrderController::class, 'store'])->name('order.store');
    Route::post('/store/order-information/update', [\App\Http\Controllers\Web\Store\OrderController::class, 'update'])->name('order.update');

    //    Start Evaluate Routers
    Route::post('/store/product/{slug}/evaluate', [\App\Http\Controllers\Web\Store\EvaluateController::class, 'store'])->name('product.evaluate');
    //    Start Get Coupon Route
    Route::get('coupons/get/{id}', [\App\Http\Controllers\Web\CouponController::class, 'get'])->name('coupon.get');

    //    Start Routes of Ads
    Route::get('/estate/create', [\App\Http\Controllers\Web\AdController::class, 'create'])->name('ads.create');

    Route::post('/estate/submit', [\App\Http\Controllers\Web\AdController::class, 'store'])->name('ads.store');

    //    get cities

});

Route::view('/admin', 'admin.index');


Route::group(['middleware' => 'auth:admin', 'as' => 'admin.', 'name' => 'admin', 'prefix' => 'admin'], function () {
    Route::get('/', ['App\Http\Controllers\Admin\AdminController', 'index'])->name('index');

    Route::group(['as' => 'store.', 'name' => 'admin', 'prefix' => '/store'], function () {
        Route::get('/', [\App\Http\Controllers\Admin\Store\StoreController::class, 'index'])->name('store.index');
        Route::get('/categories/create', [\App\Http\Controllers\Admin\Store\CategoryController::class, 'create'])->name('category.create');
        Route::post('/categories/store', [\App\Http\Controllers\Admin\Store\CategoryController::class, 'store'])->name('category.store');
        Route::get('/categories', [\App\Http\Controllers\Admin\Store\CategoryController::class, 'index'])->name('category');
        Route::get('/categories/{slug}', [\App\Http\Controllers\Admin\Store\CategoryController::class, 'show'])->name('category.show');
        Route::get('/categories/edit/{slug}', [\App\Http\Controllers\Admin\Store\CategoryController::class, 'edit'])->name('category.edit');
        Route::post('/categories/update/{id}', ['App\Http\Controllers\Admin\Store\CategoryController', 'update'])->name('category.update');
        Route::post('categories/delete/{slug}', [\App\Http\Controllers\Admin\Store\CategoryController::class, 'destroy'])->name('category.destroy');
        Route::resource('sizes', \App\Http\Controllers\Admin\Store\SizeController::class)->parameters(['sizes' => 'id']);
        Route::resource('colors', \App\Http\Controllers\Admin\Store\ColorController::class)->parameters(['colors' => 'id']);
        Route::resource('products', \App\Http\Controllers\Admin\Store\ProductController::class)->parameters(['products' => 'slug']);
        Route::resource('orders', \App\Http\Controllers\Admin\Store\OrderController::class)->parameters(['orders' => 'id']);
        Route::resource('coupons', \App\Http\Controllers\Admin\CouponController::class)->parameters(['orders' => 'id']);
    });

    Route::resource('/service', ServiceController::class)->parameters(['service' => 'slug']);
    Route::group(['as' => 'estates.', 'name' => 'admin', 'prefix' => '/estate'], function () {
        Route::resource('/citys', CityController::class)->parameters(['citys' => 'id']);
        Route::resource('/categories', CategoryController::class)->parameters(['categories' => 'id']);
        Route::resource('/sub-category', SubCategoryController::class)->parameters(['categories' => 'id']);
        Route::resource('/countries', CountryControoler::class)->parameters(['countries' => 'id']);
        Route::resource('/ads', \App\Http\Controllers\Admin\Estate\AdController::class)->parameters(['ads' => 'id']);
        Route::get('/ads/status/{id}', [\App\Http\Controllers\Admin\Estate\AdController::class, 'status'])->name('ads.status');
        Route::resource('/agents', AgentController::class)->parameters(['agents' => 'id']);
        Route::resource('/attacheds', AttachedController::class)->parameters(['attacheds' => 'id']);
        Route::resource('/attachments', WriteAttachmentController::class)->parameters(['attachments' => 'id']);
        Route::get('/add/attachments/{slug}', [AddWriteAttachmentsToAdController::class, 'create'])->name('attachment.ad.add');
        Route::post('/create/attachments/{slug}', [AddWriteAttachmentsToAdController::class, 'store'])->name('attachment.ad.store');

resources/views/admin/layouts/components/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; 2021 <a href="https://closer-software.com/">Closer-Software</a>.</strong>
    All rights reserved.
</footer>

resources/views/admin/layouts/components/head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title> @yield('title')</title>
<!-- Tell the browser to be responsive to screen width -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Font Awesome -->
<link rel="stylesheet" href="{{ asset('assets/admin-assets/plugins/fontawesome-free/css/all.min.css') }}">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- Tempusdominus Bbootstrap 4 -->
<link rel="stylesheet" href="{{ asset('assets/admin-assets/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}">
<!-- iCheck -->
<link rel="stylesheet" href="{{ asset('assets/admin-assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
<!-- JQVMap -->
<link rel="stylesheet" href="{{ asset('assets/admin-assets/plugins/jqvmap/jqvmap.min.css') }}">
<!-- Theme style -->
<link rel="stylesheet" href="{{ asset('assets/admin-assets/dist/css/adminlte.min.css') }}">
<!-- overlayScrollbars -->
<link rel="stylesheet" href="{{ asset('assets/admin-assets/plugins/overlayScrollbars/css/OverlayScrollbars.min.css') }}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{{ asset('assets/admin-assets/plugins/daterangepicker/daterangepicker.css') }}">
<!-- summernote -->
<link rel="stylesheet" href="{{ asset('assets/admin-assets/plugins/summernote/summernote-bs4.css') }}">
<!-- Google Font: Source Sans Pro -->
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
<!-- Bootstrap 4 RTL -->
<link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css">
<!-- Custom style for RTL -->
<link rel="stylesheet" href="{{ asset('assets/admin-assets/dist/css/custom.css') }}">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Tajawal:wght@500&display=swap" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />


<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.3/basic.min.css" integrity="sha512-MeagJSJBgWB9n+Sggsr/vKMRFJWs+OUphiDV7TJiYu+TNQD9RtVJaPDYP8hA/PAjwRnkdvU+NsTncYTKlltgiw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

resources/views/admin/layouts/components/navbar.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
    </ul>
    <div class="mr-auto-navbav">
        <a href="{{ route('admin.admin.logout') }}" class="mr-auto ml-0 btn btn-light text-danger">
            Logout
        </a>
    </div>

</nav>
<!-- /.navbar -->

resources/views/admin/layouts/components/scripts.blade.php
<!-- jQuery -->
<script src="{{ asset('assets/admin-assets/plugins/jquery/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('assets/admin-assets/plugins/jquery-ui/jquery-ui.min.js') }}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 rtl -->
<script src="https://cdn.rtlcss.com/bootstrap/v4.2.1/js/bootstrap.min.js"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('assets/admin-assets/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- ChartJS -->
<script src="{{ asset('assets/admin-assets/plugins/chart.js/Chart.min.js') }}"></script>
<!-- Sparkline -->
<script src="{{ asset('assets/admin-assets/plugins/sparklines/sparkline.js') }}"></script>
<!-- JQVMap -->
{{--<script src="{{ asset('assets/admin-assets/plugins/jqvmap/jquery.vmap.min.js') }}"></script>--}}
<script src="{{ asset('assets/admin-assets/plugins/jqvmap/maps/jquery.vmap.world.js') }}"></script>
<!-- jQuery Knob Chart -->
<script src="{{ asset('assets/admin-assets/plugins/jquery-knob/jquery.knob.min.js') }}"></script>

<!-- daterangepicker -->
<script src="{{ asset('assets/admin-assets/plugins/moment/moment.min.js') }}"></script>
<script src="{{ asset('assets/admin-assets/plugins/daterangepicker/daterangepicker.js') }}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ asset('assets/admin-assets/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
<!-- Summernote -->
<script src="{{ asset('assets/admin-assets/plugins/summernote/summernote-bs4.min.js') }}"></script>

<script src="{{ asset('assets/admin-assets/plugins/summernote/summernote-rtl-plugin/summernote-ext-rtl.js') }}"></script>
<!-- overlayScrollbars -->
<script src="{{ asset('assets/admin-assets/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('assets/admin-assets/dist/js/adminlte.js') }}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{ asset('assets/admin-assets/dist/js/pages/dashboard.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('assets/admin-assets/dist/js/demo.js') }}"></script>
<!-- Select 2 -->

<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<!-- sweet alert -->
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.3/min/dropzone.min.js" integrity="sha512-oQq8uth41D+gIH/NJvSJvVB85MFk1eWpMK6glnkg6I7EdMqC1XVkW7RxLheXwmFdG03qScCM7gKS/Cx3FYt7Tg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

resources/views/admin/layouts/components/sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
        <img src="{{ asset('assets/admin-assets/dist/img/AdminLTELogo.png') }}" alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">Global4in</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                @if(Auth::user()->photo)
                    <img src='{{ asset('assets/admin-assets/dist/img/user2-160x160.jpg') }}'
                         class='img-circle elevation-2' alt='User Image'>
                @else
                    <i class="fa fa-user" style="font-size: 30px"></i>
                @endif
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ Auth::user()->name }}</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                <li class="nav-item has-treeview {{ Route::is('admin.store.*') ? 'active menu-open' : null }}">
                    <a href="#" class="nav-link {{ Route::is('admin.store.*') ? 'active' : null }} ">
                        <i class="nav-icon fas fa-store-alt"></i>
                        <p>
                            اﻟﻤﺘﺠﺮ
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('admin.store.products.index') }}"
                               class="nav-link {{ Route::is('admin.store.products.*') ? 'active' : null }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>اﻟﻤﻨﺘﺠﺎﺕ</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin.store.category') }}"
                               class="nav-link {{ Route::is('admin.store.category.*') || Route::is('admin.store.category') ? 'active' : null }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>اﻻﻗﺴﺎﻡ</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin.store.colors.index') }}"
                               class="nav-link {{ Route::is('admin.store.colors.*') ? 'active' : null }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>اﻻﻟﻮاﻥ</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin.store.sizes.index') }}"
                               class="nav-link {{ Route::is('admin.store.sizes.*') ? 'active': null }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>اﻟﻤﻘﺎﺳﺎﺕ</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin.store.orders.index') }}"
                               class="nav-link {{ Route::is('admin.store.sizes.*') ? 'active': null }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p> اﻟﻄﻠﺒﺎﺕ@if(\App\Models\Order::query()->where('read', 0)->count() > 0) <span class="bg-danger rounded px-2">{{\App\Models\Order::query()->where('read', 0)->count()}}</span> @endif</p>
                            </a>
                        </li>
                    </ul>
                <li class="nav-item">
                    <a href="{{ route('admin.service.index') }}" class="nav-link {{ Route::is('admin.service.*') ? 'active' : null }} ">
                        <i class="fas fa-star nav-icon"></i>
                        <p>ﺧﺪﻣﺎﺕ</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.partner.index') }}" class="nav-link {{ Route::is('admin.partner.*') ? 'active' : null }} ">
                        <i class="fas fa-star nav-icon"></i>
                        <p>اﻟﺸﺮﻛﺎء</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.store.coupons.index') }}" class="nav-link {{ Route::is('admin.store.coupons.*') ? 'active' : null }} ">
                        <i class="fas fa-star nav-icon"></i>
                        <p>اﻟﻜﻮﺑﻮﻧﺎﺕ</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.commercial.index') }}" class="nav-link {{ Route::is('admin.commercial.*') ? 'active' : null }} ">
                        <i class="fas fa-star nav-icon"></i>
                        <p>اﻟﺪﻋﺎﻳﺔ</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin.contact.index') }}" class="nav-link {{ Route::is('admin.contact.*') ? 'active' : null }} ">
                        <i class="fas fa-star nav-icon"></i>
                        <p>اﻟﺮﺳﺎﺋﻞ@if(\App\Models\Contact::query()->where('is_read', 0)->count() > 0) <span class="bg-danger rounded px-2">{{\App\Models\Contact::query()->where('is_read', 0)->count()}}</span> @endif</p>
                    </a>
                </li>
                <li class="nav-item has-treeview {{ Route::is('admin.estates.*') ? 'active menu-open' : null }}">
                    <a href="#" class="nav-link {{ Route::is('admin.estates.*') ? 'active' : null }} ">
                        <i class="nav-icon fas fa-store-alt"></i>
                        <p>
                            اﻟﻌﻘﺎﺭاﺕ
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('admin.estates.countries.index') }}"
                               class="nav-link {{ Route::is('admin.estates.countries.*') ? 'active' : null }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>اﻟﺪﻭﻝ</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin.estates.citys.index') }}"
                               class="nav-link {{ Route::is('admin.estates.citys.*') ? 'active' : null }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>اﻟﻤﺪﻥ</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin.estates.agents.index') }}"
                               class="nav-link {{ Route::is('admin.estates.agents.*') ? 'active' : null }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>اﻟﻮﻛﻼء</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin.estates.attacheds.index') }}"
                               class="nav-link {{ Route::is('admin.estates.attacheds.*') ? 'active' : null }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>اﻟﻤﺮﻓﻘﺎﺕ</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin.estates.attachments.index') }}"
                               class="nav-link {{ Route::is('admin.estates.attachments.*') ? 'active' : null }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>اﻟﻤﺮﻓﻘﺎﺕ اﻟﻜﺘﺎﺑﻴﺔ</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin.estates.categories.index') }}"
                               class="nav-link {{ Route::is('admin.estates.categories.*') ? 'active' : null }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>نوع العقار</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin.estates.sub-category.index') }}"
                               class="nav-link {{ Route::is('admin.estates.sub-category.*') ? 'active' : null }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>صفة العقار</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin.estates.ads.index') }}"
                               class="nav-link {{ Route::is('admin.estates.ads.*') ? 'active' : null }}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>اﻋﻼﻧﺎﺕ اﻟﻌﻘﺎﺭاﺕ</p>
                            </a>
                        </li>
                    </ul>
                <li class="nav-item">
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>