routes/web.php
<?php

use App\Http\Controllers\Admin\Estate\CityController;
use App\Http\Controllers\Admin\Estate\AddWriteAttachmentsToAdController;
use App\Http\Controllers\Admin\Estate\AgentController;
use App\Http\Controllers\Admin\Estate\AttachedController;
use App\Http\Controllers\Admin\Estate\CategoryController;
use App\Http\Controllers\Admin\Estate\CountryControoler;
use App\Http\Controllers\Admin\Estate\GetAttachedController;
use App\Http\Controllers\Admin\Estate\GetSubCategoryController;
use App\Http\Controllers\Admin\Estate\WriteAttachmentController;
use App\Http\Controllers\Admin\ServiceController;
use App\Http\Controllers\Admin\SubCategoryController;
use App\Http\Controllers\Web\AdController;
use App\Http\Controllers\Web\CommercialController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'website.index')->name('website.index');
Route::view('/about', 'website.about')->name('website.about');
Route::view('/services', 'website.services')->name('website.services');
Route::view('/contact', 'website.contact')->name('website.contact');
Route::view('/faq', 'website.FAQ')->name('website.FAQ');
Route::view('/terms-conditions', 'website.terms-conditions')->name('website.terms-conditions');
Route::view('/privacy', 'website.terms-conditions')->name('website.privacy');
Route::view('/estate', 'website.estate')->name('website.estate');

Route::get('/commercial', [\App\Http\Controllers\web\PagesController::class, 'commercial'])->name('website.commercial');
Route::get('/commerical/{slug}', [CommercialController::class, 'show'])->name('commercial.show');
Route::get('/commercial/download-pdf/{slug}', [CommercialController::class, 'download'])->name('commercial.download');
Route::get('/store', [\App\Http\Controllers\web\PagesController::class, 'store'])->name('website.store');

Route::get('/register', [\App\Http\Controllers\Web\Auth\RegisterController::class, 'register'])->name('register.index');
Route::post('/register', [\App\Http\Controllers\Web\Auth\RegisterController::class, 'submit'])->name('register.submit');
Route::get('/login', [\App\Http\Controllers\Web\Auth\LoginController::class, 'login'])->name('login.index');
Route::post('/login', [\App\Http\Controllers\Web\Auth\LoginController::class, 'submit'])->name('login.submit');
Route::get('/products', [\App\Http\Controllers\Web\Store\StoreController::class, 'index'])->name('store.index');
Route::get('/store/category/{slug}', [\App\Http\Controllers\Web\Store\StoreController::class, 'category'])->name('store.category');
Route::get('store/product/{slug}', [\App\Http\Controllers\Web\Store\ProductController::class, 'index'])->name('product.index');
Route::get('store/search/', [\App\Http\Controllers\Web\Store\ProductController::class, 'search'])->name('product.search');
Route::get('store/wishlist', [\App\Http\Controllers\Web\Store\WishlistController::class, 'index'])->name('store.wishlist');
Route::get('store/wishlist/{slug}', [\App\Http\Controllers\Web\Store\WishlistController::class, 'add'])->name('store.wishlist.add');
Route::get('store/wishlist/remove/{id}', [\App\Http\Controllers\Web\Store\WishlistController::class, 'remove'])->name('store.wishlist.remove');
Route::get('coupons', [\App\Http\Controllers\Web\CouponController::class, 'index'])->name('coupon.index');
Route::get('coupons/search/', [\App\Http\Controllers\Web\CouponController::class, 'search'])->name('coupon.search');
Route::get('/ads', [\App\Http\Controllers\Web\AdController::class, 'index'])->name('ads.index');
Route::get('/ad/search/', [\App\Http\Controllers\Web\AdController::class, 'search'])->name('ads.search');
Route::get('/ads/country/{country_id}', [AdController::class, 'countryAd'])->name('ads.country');
Route::get('/ads/{slug}', [\App\Http\Controllers\Web\AdController::class, 'show'])->name('ads.show');
Route::get('/ad/{slug}', [\App\Http\Controllers\Web\AdController::class, 'dwonload'])->name('ads.chart_download');
Route::get('/service/{slug}', [\App\Http\Controllers\Web\ServicesController::class, 'show'])->name('service.show');
Route::post('/contact/store', [\App\Http\Controllers\Admin\ContactUsController::class, 'store'])->name('contact.store');


Route::get('/cities/{id}', [\App\Http\Controllers\Web\AdController::class, 'getCities'])->name('ads.cities');
Route::group(['middleware' => 'auth:web'], function () {
    //    Start Cart Routers
    Route::get('/my-cart', [\App\Http\Controllers\Web\Store\CartController::class, 'index'])->name('cart.index');
    Route::post('/my-cart/add/{slug}', [\App\Http\Controllers\Web\Store\CartController::class, 'add'])->name('cart.add');
    Route::get('my-cart/remove/{id}', [\App\Http\Controllers\Web\Store\CartController::class, 'remove'])->name('cart.remove');
    //    End Cart Routers

    //    Start Checkout Routers
    Route::get('/store/payment-checkout', [\App\Http\Controllers\Web\Store\PaymentController::class, 'index'])->name('payment.checkout');
    Route::get('/store/payment-checkout/shopper', [\App\Http\Controllers\Web\Store\PaymentController::class, 'shopper'])->name('payment.shopper');
    Route::view('/store/payment-done', 'website.checkout-status')->name('payment.status');

    //    Start Order Information Route
    Route::post('/store/order-information', [\App\Http\Controllers\Web\Store\OrderController::class, 'store'])->name('order.store');
    Route::post('/store/order-information/update', [\App\Http\Controllers\Web\Store\OrderController::class, 'update'])->name('order.update');

    //    Start Evaluate Routers
    Route::post('/store/product/{slug}/evaluate', [\App\Http\Controllers\Web\Store\EvaluateController::class, 'store'])->name('product.evaluate');
    //    Start Get Coupon Route
    Route::get('coupons/get/{id}', [\App\Http\Controllers\Web\CouponController::class, 'get'])->name('coupon.get');

    //    Start Routes of Ads
    Route::get('/estate/create', [\App\Http\Controllers\Web\AdController::class, 'create'])->name('ads.create');

    Route::post('/estate/submit', [\App\Http\Controllers\Web\AdController::class, 'store'])->name('ads.store');

    //    get cities

});

Route::view('/admin', 'admin.index');


Route::group(['middleware' => 'auth:admin', 'as' => 'admin.', 'name' => 'admin', 'prefix' => 'admin'], function () {
    Route::get('/', ['App\Http\Controllers\Admin\AdminController', 'index'])->name('index');

    Route::group(['as' => 'store.', 'name' => 'admin', 'prefix' => '/store'], function () {
        Route::get('/', [\App\Http\Controllers\Admin\Store\StoreController::class, 'index'])->name('store.index');
        Route::get('/categories/create', [\App\Http\Controllers\Admin\Store\CategoryController::class, 'create'])->name('category.create');
        Route::post('/categories/store', [\App\Http\Controllers\Admin\Store\CategoryController::class, 'store'])->name('category.store');
        Route::get('/categories', [\App\Http\Controllers\Admin\Store\CategoryController::class, 'index'])->name('category');
        Route::get('/categories/{slug}', [\App\Http\Controllers\Admin\Store\CategoryController::class, 'show'])->name('category.show');
        Route::get('/categories/edit/{slug}', [\App\Http\Controllers\Admin\Store\CategoryController::class, 'edit'])->name('category.edit');
        Route::post('/categories/update/{id}', ['App\Http\Controllers\Admin\Store\CategoryController', 'update'])->name('category.update');
        Route::post('categories/delete/{slug}', [\App\Http\Controllers\Admin\Store\CategoryController::class, 'destroy'])->name('category.destroy');
        Route::resource('sizes', \App\Http\Controllers\Admin\Store\SizeController::class)->parameters(['sizes' => 'id']);
        Route::resource('colors', \App\Http\Controllers\Admin\Store\ColorController::class)->parameters(['colors' => 'id']);
        Route::resource('products', \App\Http\Controllers\Admin\Store\ProductController::class)->parameters(['products' => 'slug']);
        Route::resource('orders', \App\Http\Controllers\Admin\Store\OrderController::class)->parameters(['orders' => 'id']);
        Route::resource('coupons', \App\Http\Controllers\Admin\CouponController::class)->parameters(['orders' => 'id']);
    });

    Route::resource('/service', ServiceController::class)->parameters(['service' => 'slug']);
    Route::group(['as' => 'estates.', 'name' => 'admin', 'prefix' => '/estate'], function () {
        Route::resource('/citys', CityController::class)->parameters(['citys' => 'id']);
        Route::resource('/categories', CategoryController::class)->parameters(['categories' => 'id']);
        Route::resource('/sub-category', SubCategoryController::class)->parameters(['categories' => 'id']);
        Route::resource('/countries', CountryControoler::class)->parameters(['countries' => 'id']);
        Route::resource('/ads', \App\Http\Controllers\Admin\Estate\AdController::class)->parameters(['ads' => 'id']);
        Route::get('/ads/status/{id}', [\App\Http\Controllers\Admin\Estate\AdController::class, 'status'])->name('ads.status');
        Route::resource('/agents', AgentController::class)->parameters(['agents' => 'id']);
        Route::resource('/attacheds', AttachedController::class)->parameters(['attacheds' => 'id']);
        Route::resource('/attachments', WriteAttachmentController::class)->parameters(['attachments' => 'id']);
        Route::get('/add/attachments/{slug}', [AddWriteAttachmentsToAdController::class, 'create'])->name('attachment.ad.add');
        Route::post('/create/attachments/{slug}', [AddWriteAttachmentsToAdController::class, 'store'])->name('attachment.ad.store');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $guarded;

    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/Admin/Estate/CategoryController.php
<?php

namespace App\Http\Controllers\Admin\Estate;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Estate\CategoryRequest;
use App\Models\AdCategory;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = AdCategory::query()->paginate(10);
        return view('admin.pages.Estates.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.Estates.categories.create-edite');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        AdCategory::query()->create($request->all());
        session()->flash('success', 'تم اضافة القسم بنجاح');
        return redirect()->route('admin.estates.categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = AdCategory::query()->findOrFail($id);
        return view('admin.pages.Estates.categories.create-edite', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, $id)
    {
        $category = AdCategory::query()->findOrFail($id);
        $category->name = $request->name;
        $category->sub_description = $request->sub_description;
        $category->keywords = $request->keywords;
        $category->save();
        session()->flash('success', 'ام التعديل بنجاح');
        return redirect()->route('admin.estates.categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = AdCategory::query()->findOrFail($id);
        $category->delete();
        session()->flash('success', 'تم حذ القسم بنجاح');
        return redirect()->route('admin.estates.categories.index');
    }
}

app/Http/Controllers/Admin/Store/CategoryController.php
<?php

namespace App\Http\Controllers\Admin\Store;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Store\CreateCategoryRequest;
use App\Http\Requests\Admin\Store\EditCategoryRequest;
use Illuminate\Http\Request;
use App\Models\Category;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image;

class CategoryController extends Controller
{
    public function index()
    {
        $categories = Category::latest()->paginate(10);
        return view('admin.pages.Store Section.Category.index', compact('categories'));
    }

    public function edit($slug)
    {
        $category_id = DB::table('categories')->where('slug', $slug)->first();
        $category = Category::findOrFail($category_id->id);
        return view('admin.pages.Store Section.Category.edit', compact('category'));
    }

    public function update(EditCategoryRequest $request, $id)
    {
        $category = Category::findOrFail($id);
        if ($request->has('image'))
        {
            \Storage::delete('/public/'. $category->image);
            $time = time();
            $ext = $request->image->getClientOriginalExtension();
            $fileName = $time.uniqid().'.'.$ext;
            $image = Image::make($request->image->getRealPath());
            $image->resize(1350, 800);
            $image->save(public_path('storage/Images/Categories/' . $fileName));
            $category->image = 'Images/Categories/' . $fileName;
        }
        $category->name = $request->name;
        $category->sub_description = $request->sub_description;
        $category->keywords = $request->keywords;
        $category->slug = Str::slug($request->name, '-');
        $category->save();
        session()->flash('success', 'تم التعديل بنجاح');
        return redirect()->route('admin.store.category');
    }

    public function show($slug)
    {
        $category_id = DB::table('categories')->where('slug', $slug)->first();
        $category = Category::findOrFail($category_id->id);
        return view('admin.pages.Store Section.Category.show', compact('category'));
    }

    public function create()
    {
        return view('admin.pages.Store Section.Category.edit');
    }

    public function store(CreateCategoryRequest $request): \Illuminate\Http\RedirectResponse
    {
        $time = time();
        $ext = $request->image->getClientOriginalExtension();
        $fileName = $time.uniqid().'.'.$ext;
        $image = Image::make($request->image->getRealPath());
        $image->resize(1350, 800);
        $image->save(public_path('storage/Images/Categories/' . $fileName));
        Category::create([
            'name' => $request->name,
            'sub_description' => $request->sub_description,
            'keywords' => $request->keywords,
            'slug' => Str::slug($request->name, '-'),
            'image' => 'Images/Categories/' . $fileName
        ]);
        session()->flash('success', 'تم إضافة القسم بنجاح');
        return redirect()->route('admin.store.category');
    }
    public function destroy($slug)
    {
        $category = Category::query()->where('slug', $slug)->first();
        \Storage::delete('/public/'. $category->image);
        $category->delete();
        session()->flash('success', 'تم حذف القسم بنجاح');
        return redirect()->route('admin.store.category');
    }
}

resources/views/admin/pages/Store Section/Category/edit.blade.php
@extends('admin.layouts.app')
@section('title', isset($category) ? 'تعديل علي القسم' : 'اضافة')
@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <form
                        enctype="multipart/form-data"
                        action="{{ isset($category) ? route('admin.store.category.update', $category->id) : route('admin.store.category.store') }}"
                        method="post">
                        @csrf
                        <div class="form-group">
                            <label for="name">الاسم</label>
                            <input type="text" class="form-control" id="name" name="name"
                                   value="{{ isset($category) ? $category->name : old('name') }}" placeholder="الاسم">
                        </div>
                        <div class="form-group">
                            <label for="image">الصورة</label>
                            @if(isset($category))
                                <img src="{{ asset('storage/'. $category->image) }}" class="rounded" width="350" alt="">
                            @endif
                            <input type="file" name="image" id="image" class="form-control-file" required/>
                        </div>
                        <div class="form-group">
                            <label for="sub_description">الوصف القصير</label>
                            <textarea name="sub_description" id="sub_description" PLACEHOLDER="الوصف القصير"
                                      class="form-control">{{ isset($category) ? $category->sub_description : old('sub_description') }}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="keywords">الكلمات الدلالية</label>
                            <textarea name="keywords" id="keywords" class="form-control"
                                      placeholder="الكلمات الدلالية">{{ isset($category) ? $category->keywords : old('keywords') }}</textarea>
                        </div>

                        <button class="btn btn-success">{{ isset($category) ? 'تعديل' : 'اضافة' }}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/pages/Store Section/Category/index.blade.php
@extends('admin.layouts.app')
@section('title', 'اقسام منتجات المتجر')
@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 my-2">
                    <a href="{{ route('admin.store.category.create') }}" class="btn btn-success">اضافة قسم</a>
                </div>
                <div class="col-12 m-auto">
                    <table class="table m-auto table-striped table-responsive-sm">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>اسم القسم</th>
                            <th>الوصف القصير</th>
                            <th>العمليات</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($categories as $key => $category)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{ $category->name }}</td>
                                <td>{{ $category->sub_description }}</td>
                                <td class="d-flex"><a href="{{ route('admin.store.category.show', $category->slug) }}"
                                                      class="btn btn-info mx-1">عرض</a> <a
                                        href="{{ route('admin.store.category.edit', $category->slug) }}"
                                        class="btn btn-success mx-1">تعديل</a>
                                    <form method="post" action="{{ route('admin.store.category.destroy', $category->slug) }}">
                                        @csrf
                                        <button class="btn btn-danger mx-1">حذف</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    <div class="col-12 d-flex justify-content-center">
                        {!! $categories->links() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/pages/Store Section/Category/show.blade.php
@extends('admin.layouts.app')

@section('title', 'عرض معلومات القسم')

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="p-2 ">
                                <h4>الاسم</h4>
                                <p class="text-gray">
                                    {{ $category->name }}
                                </p>
                            </div>
                            <div class="p-2 ">
                                <h4>الصورة</h4>
                                <p class="text-gray">
                                    <img src="{{ asset('storage/'. $category->image) }}" alt="">
                                </p>
                            </div>
                            <div class="p-2 ">
                                <h4>الوصف القصير</h4>
                                <p class="text-gray">
                                    {{ $category->sub_description }}
                                </p>
                            </div>
                            <div class="p-2 ">
                                <h4>الكلمات الدلالية</h4>
                                <p class="text-gray">
                                    {{ $category->keywords }}
                                </p>
                            </div>
                            <hr>
                            <a href="{{ route('admin.store.category.edit', $category->slug) }}" class="btn btn-info">تعديل</a>
                            <a href="{{ url()->previous() }}" class="btn badge-dark">رجوع</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection